# azure-pipelines.yml — Windows, two stages, pass file via artifacts
trigger:
- main


pool:
  name: 12345

stages:
- stage: Create
  displayName: 'Creating file'
  jobs:
  - job: CreateJob
    steps:
    - checkout: self

    - powershell: |
        Write-Host "creating file"
        $path = "$(Build.SourcesDirectory)\test.txt"
        "Hello from Create stage" | Set-Content -Path $path -Encoding utf8
        Get-Content $path
      displayName: Create test.txt

    - task: PublishPipelineArtifact@1
      displayName: Publish test.txt as pipeline artifact
      inputs:
        targetPath: '$(Build.SourcesDirectory)\test.txt'
        artifact: 'test-file'
        publishLocation: 'pipeline'

- stage: Write
  displayName: 'Writing in file'
  dependsOn: Create
  jobs:
  - job: WriteJob
    steps:
    - checkout: none

    - download: current
      artifact: 'test-file'   # -> $(Pipeline.Workspace)\test-file\test.txt

    - powershell: |
        $path = "$(Pipeline.Workspace)\test-file\test.txt"
        Write-Host "Before:"
        Get-Content $path
        "This is new content." | Set-Content -Path $path -Encoding utf8
        Write-Host "`nAfter:"
        Get-Content $path
      displayName: Overwrite content
