# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pool: 12345


stages: 
  - stage: Create
    displayName: 'Creating file'
    jobs:
      - job: CreateJob
        steps:
        - script: |
            echo creating file
            cat test.txt
          displayName: Install deps

  - stage: Write
    displayName: 'Writing in file'
    jobs:
      - job: WriteJob
        steps:
        - script: |
            echo writing in file
            echo "This is new content." > test.txt
          displayName: Install deps
          

